Bump `@metamask/rpc-errors` to `^6.2.0` (#3954)
## Explanation

This bumps `@metamask/rpc-errors` to `^6.2.0` to solve a type error when
using `@metamask/permission-controller`:

```
node_modules/@metamask/permission-controller/dist/errors.d.ts:22:107 - error TS7016: Could not find a declaration file for module '@metamask/rpc-errors/dist/utils'. '/Users/morten/Development/MetaMask/snaps/node_modules/@metamask/rpc-errors/dist/utils.js' implicitly has an 'any' type.
```

## Changelog

<!--
If you're making any consumer-facing changes, list those changes here as
if you were updating a changelog, using the template below as a guide.

(CATEGORY is one of BREAKING, ADDED, CHANGED, DEPRECATED, REMOVED, or
FIXED. For security-related issues, follow the Security Advisory
process.)

Please take care to name the exact pieces of the API you've added or
changed (e.g. types, interfaces, functions, or methods).

If there are any breaking changes, make sure to offer a solution for
consumers to follow once they upgrade to the changes.

Finally, if you're only making changes to development scripts or tests,
you may replace the template below with "None".
-->

### `@metamask/approval-controller`

- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.

### `@metamask/assets-controllers`

- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.

### `@metamask/json-rpc-engine`

- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.

### `@metamask/network-controller`

- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.

### `@metamask/permission-controller`

- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.

### `@metamask/queued-request-controller`

- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.

### `@metamask/rate-limit-controller`

- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.

### `@metamask/signature-controller`

- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.

### `@metamask/transaction-controller`

- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.

### `@metamask/user-operation-controller`

- **CHANGED**: Bump `@metamask/rpc-errors` from `^6.1.0` to `^6.2.0`.

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or
updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category
above as appropriate