WF docs: Fix building & move Docusaurus scripts under 'site:'
This commit fixes a couple of related issues with the
`wallet-framework-docs` package:

\## Build issues

Running the `dev` or `build` package scripts under
`@metamask/wallet-framework-docs` stopped working after the ESM
migration. It seems that Docusaurus — or Docusaurus's usage of Webpack —
is not fully compatible with ESM, as it produces the following error:

```
[ERROR] Error: Unable to build website for locale en.
at tryToBuildLocale (~/core/node_modules/@docusaurus/core/lib/commands/build/build.js:76:15)
at async ~/core/node_modules/@docusaurus/core/lib/commands/build/build.js:34:9
at async mapAsyncSequential (~/core/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
at async Command.build (~/core/node_modules/@docusaurus/core/lib/commands/build/build.js:33:5)
at async Promise.all (index 0)
at async runCLI (~/core/node_modules/@docusaurus/core/lib/commands/cli.js:56:5)
at async file://~/core/node_modules/@docusaurus/core/bin/docusaurus.mjs:44:3 {
[cause]: TypeError: require.resolveWeak is not a function
at 9219 (server.bundle.js:30913:17)
at __webpack_require__ (server.bundle.js:31109:31)
at 8672 (server.bundle.js:20639:57)
at __webpack_require__ (server.bundle.js:31109:31)
at 6658 (server.bundle.js:30990:66)
at __webpack_require__ (server.bundle.js:31109:31)
at 7856 (server.bundle.js:21514:55)
at __webpack_require__ (server.bundle.js:31109:31)
at 5976 (server.bundle.js:21643:46)
at __webpack_require__ (server.bundle.js:31109:31)
}
```

To fix this, I've removed `"type": "module"` from
`wallet-framework-docs` so it is no longer ESM-only. Right now, that
doesn't cause any issues because the package is private. If we end up
publishing this package for any reason, we'll need to figure out a
different solution, but this solves the problem for now.

Making that change forced me to make an exception for
`wallet-framework-docs` in the Yarn constraints.

> [!NOTE]
> `platform-api-docs` also uses Docusaurus, but unexplicably, running
> `yarn docs:platform-api:build` seems to work just fine.

\## Content issues

Since we don't try to build `wallet-framework-docs` in CI, some of the
links in the docs were broken and we didn't know about them. I've fixed
them in this commit, too.